[theme]
theme = "/home/jervw/.config/i3/bar/theme.toml"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.rot-str(20) $play $next |}"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization"
format_alt = " $icon $frequency"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(1) "
format_alt = " $icon_swap $swap_free.eng(3,B,M)/$swap_total.eng(3,B,M)($swap_used_percents.eng(2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "battery"
format = " $icon  $percentage "
missing_format = ""

[[block]]
block = "time"
interval = 60
format = "$icon %d/%m %R "

