[theme]
theme = "solarized-dark"

[icons]
icons = "awesome"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $play $next |}"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization"
format_alt = " $icon $frequency"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "battery"
format = " $icon  $percentage "
missing_format = ""

[[block]]
block = "time"
interval = 60
format = "$icon %d/%m %R "

