theme = "space-villain"
icons = "awesome"

[[block]]
block = "music"
max_width = 25

[[block]]
block = "cpu"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;M}/{mem_total;M:1} ({mem_used_percents:1})"
format_swap = "{swap_used;M}/{swap_total;M}({swap_used_percents})"

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)"
interval = 600

[[block]]
block = "time"
interval = 5
format = "%a %-d. %R"
