[theme]
theme = "nord-dark"

[icons]
icons = "awesome"

[[block]]
block = "music"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization"
format_alt = " $icon $frequency"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(1) "
format_alt = " $icon_swap $swap_free.eng(3,B,M)/$swap_total.eng(3,B,M)($swap_used_percents.eng(2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "time"
interval = 5
format = "%a %-d. %R"
