# prefix is C-a
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# start index from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g mouse on

# easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# splits
bind-key [ split-window -v
bind-key ] split-window -h

# vim master race
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# use vim-like keys for splits and windows
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

bind-key C command-prompt -p "New session name: " "new-session -s '%%'"

# bind pane and window killing without prompt
bind-key q kill-pane
bind-key x kill-window

set -ga terminal-overrides ",xterm-256color:Tc"

# statusbar
set -g status-position top
set -g status-interval 1
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

setw -g window-status-current-style "bg=blue"
setw -g window-status-current-format '#{pane_current_command}'
setw -g window-status-format '#{pane_current_command}'

set -sg escape-time 0
setw -g c0-change-trigger 100
setw -g c0-change-interval 20



## Plugins ##
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
